---
date: "2023-08-31T00:00:00Z"
external_link: ""
image: 
  caption: Photo by rawpixel on Unsplash
  focal_point: Smart
links:
# - icon: twitter
#   icon_pack: fab
#   name: Follow
#   url: https://twitter.com/georgecushen
# slides: example
summary: Standardized Index Values of Major Stock Market Indices
tags:
- MARKETS
title: Stock Markets
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---
<!-- {{< load-plotly >}} -->

Featured below are the indeces of major stock marekts around the world. 

### Equity Indices (Normalized 2007-01-04 = 100%)
<br> 

<button onclick="toggleFullscreen('iframe1')" style="font-size: 14px; padding: 5px 15px; border: none; border-radius: 20px; background-color: #1664c0; color: white; cursor: pointer; transition: background-color 0.3s;" onmouseover="this.style.backgroundColor='#0056b3'" onmouseout="this.style.backgroundColor='#007BFF'">Open in Fullscreen</button>
<iframe id="iframe1" src="StockMarketIndices1.html" width="100%" height="600px" frameborder="0"> </iframe>

```{r, include=FALSE}
StockMarketIndices1_update_date <- readRDS("~/Desktop/websiteJuly2023/content/project/StockMarketIndices/StockMarketIndices1_update_date.rds")
``` 

<br> <br> 
Last update: `r StockMarketIndices1_update_date` CET

#### Data Sources: 
* Stock Market Indices: [Yahoo Finance](https://finance.yahoo.com)
  
***


### Equity Indices
<br> 

<button onclick="toggleFullscreen('iframe2')" style="font-size: 14px; padding: 5px 15px; border: none; border-radius: 20px; background-color: #1664c0; color: white; cursor: pointer; transition: background-color 0.3s;" onmouseover="this.style.backgroundColor='#0056b3'" onmouseout="this.style.backgroundColor='#007BFF'">Open in Fullscreen</button>
<iframe id="iframe2" src="StockMarketIndices2.html" width="100%" height="600px" frameborder="0"> </iframe>

```{r, include=FALSE}
StockMarketIndices2_update_date <- readRDS("~/Desktop/websiteJuly2023/content/project/StockMarketIndices/StockMarketIndices2_update_date.rds")
``` 

<br> <br> 
Last update: `r StockMarketIndices2_update_date` CET

#### Data Sources: 
* Stock Market Indices: [Yahoo Finance](https://finance.yahoo.com)